language: java
deploy:
  - provider: releases
    api_key:
      secure: PTJwXc9yCc+8JdmpuL1z22a2WhNGyrZnsK06LZa4aJ1+vBzaNiKdijArymQsccn+E2GCfGW3H8O4OxqYWveh4DN8jZuzSdoZxiK3sEa91I+Iop6bc0zAHIZCB62v8kZlJGEf66CipC0BEGw3G73AUtS0s6sHUjU2hL8pW2iCzGY1S3NUsheQg2oR+VHRP9VXj5BkwiimFYuvvl/L7bwAgVQu8JKvtNwZpjGQwIxQWXI072dBbfk1hbDl3a+X3Yu+3EQoEe1oTHTkflFTxqpc1qrzzM3eSbqPf2grGTIyoxNvEvZl5xts5/5ajOB2N89m+cPNcnBmnDB4vwpjcItZkX/8ZPJmzTZ8kP77CUPKoYyxMUHNPbaX0YgOlEv2OcBcM5CkgG8GLFLLI5V/XscqkgyB73ImYow/jSnxwQJ+vHwTIZyE9Kkl4IocYYOkZpQqoqn4ytETHsAaWaQEemUUOREIFErrX74+Tjz/1dy0g4UNKTI13l3tNzxG37JkWzF+BCIT/73sxTtL0PwjPZbcMVK4ycEwselvRrfe7qHEXdEcH5pGEZhxJWJXDueUPo+zn70gxG9sjVgKUcQ7+cGF2TepwG+oMQEjYMYKXiFhj/kJbNmq2ZSmGipxVvBkwhJDEs6uSxWESW+SsXLE1hQj7tI1DCYy8ht6RJmzrKHSS+c=
    file_glob: true
    file: out/libs/*
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
notifications:
    slack:
      secure: nWvMVuWFfHfcCTJK0MJSXtsIzQvjGadXyeJHKdSxFbdELFtn/1rdXFEWQGXowxA/AmuHeu2J+2IfZfoH/rQC/7QNNO9knMpsd4vjxreEWEPP8SmTF/nYr8erVsny6l1hgICKISV2y0PIklXmQGINsZtVnZ5+9BXiV8XvJvK2lZnAr94k2+Jhbf9lMAb1rUrqNod1k08Vd9tney/TwDSL84EmlvrlsOSVq++m85QIHDA41pCwqPeWaqCFw8r3j2zmp5Ef/5H9ZuZjaZxEaIE/6TVNCXyGfFPZAlbBC3mIJS136QxD6P/WtnyvOJUyQqNFm0S/PHMVhsoDyJmsDZtcLYbpy5U13V8PL/zcSakaxhXuxr7lIPcTxmEpqHnAGHTDzsocNKXCrTLgFbmlJKcNcetmOo3RrxtmIEoN00bz4IfaIJGf9uPwz7IskFDfh4qtLWCQcSJSSSIKD2bfhaR9Dsmj0zegsVvXPCO/brXni7wGCOgxYGkYi89bt1e2DwX16Jo+/LKG07k/x1ApPcRxUUWySqz4Ibi/AlcZQdLjvYRoitTKg/yqvooxU8o6V6kUI2a1gfR6tTBQ62+k3k4I14BTWY5fcXlzeDZcnx5R3KSbqaeHDViSWahMtT2Og8WXdOD8BzI1vFN8S12ju/7OqUmw8H5lha6+d57kHA7XdjU=